
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_WS_URL: ws://localhost:8765
    container_name: frontend
    ports:
      - "3000:80"
    restart: unless-stopped
  backend-python:
    build:
      context: ./backend/python
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
