FROM python:3.11-slim

# Install OpenCV + image deps
RUN apt-get update && apt-get install -y \
    build-essential \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p uploads

EXPOSE 8765

CMD ["sh", "-c", "echo '💥 DOCKER IS RUNNING' && ls -la /app && python app.py"]

